services:
  fastapi:
    build: .
    container_name: api.coffeeheim.com
    command: fastapi run app/main.py --port 80
    volumes:
      - ./app:/code/app
      - ${HOME}/valheim:/mnt/valheim
    ports:
      - 8001:80
